---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Rthquake

Rthquake is a package built for the capstone course of the **Mastering Software Development in R Specialization** offered through **Johns Hopkins University on Coursera**. The aim of this package is provide a set of tools for the visualization of Earthquake data from the NOAA Significant Earthquake Database 

(National Geophysical Data Centre / World Data Service (NGDC/WDS): Significant Earthquake Database. National Geophysical Data Centre, NOAA. doi:10.7289/V5TD9V7K).

## Installation

You can install and load the released version of Rthquake with:

``` r
devtools::install_github('Paul-Draper/Rthquake', build_vignettes = TRUE)
library(Rthquake)
```

## Usage

The functionality of Rthquake is discussed in the package vignette. You can read the vignette after installing the package by running `vignette('Intro_to_Rthquake', package = 'Rthquake')`.
